==== partage 

== serveur 

trackId aller : 5a63e436714db8001447afca
trackId retour : 5a63e437714db8001447afdf

= recuperer le token pour la fourmi

curl -d "email=ant1@violet.ant&password=Prune" -X POST https://f24h2018.herokuapp.com/auth/local

= recuperer le token pour la cigale

curl -d "email=cicada@violet.ant&password=Prune" -X POST https://f24h2018.herokuapp.com/auth/local

= recuperer les graines (exemple)
Requête :
GET https://f24h2018.herokuapp.com/api/Seeds/search HTTP/1.1
Accept-Encoding: gzip,deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTYzMjMyN2YzNmQyODcwODdhMTk2YWUiLCJyb2xlIjoiY2ljYWRhIiwiaWF0IjoxNTE2NDQ4NTU5LCJleHAiOjE1MTY0NjY1NTl9.vRC4yJZ_HmY-vrr5tFbgXvbh6tjuLIPtlOyzl1jwgZQ
Host: f24h2018.herokuapp.com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

Réponse :
[
      {
      "_id": "5a5e71a2734d1d347185192c",
      "name": "La fourmilière",
      "info": "Colonie",
      "active": true,
      "type": "home",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.9844782,
            0.2415538
         ]
      }
   },
      {
      "_id": "5a5e7207734d1d347185195c",
      "name": "Epau",
      "info": "pas trop loin",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.99026,
            0.23991
         ]
      }
   },
      {
      "_id": "5a5e7228734d1d3471851968",
      "name": "CFA",
      "info": "pas trop loin",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.9827689,
            0.2328369
         ]
      }
   },
      {
      "_id": "5a5e71e2734d1d3471851942",
      "name": "Les plaines de l'arche",
      "info": "pas trop loin",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.987444,
            0.253475
         ]
      }
   },
      {
      "_id": "5a63483cf36d287087a19f59",
      "name": "Goncourt",
      "info": "après lycée Sud",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.9809281,
            0.2222387
         ]
      }
   }
]

= Liste des tracks des autres équipes

Réponse :
[{
   "_id": "5a6350688fb12f001481b340",
   "name": "test",
   "info": "ceci est un test",
   "userId": "5a5e6f43734d1d3471851818",
   "endSeedId": "5a5e7207734d1d347185195c",
   "endDate": "2018-01-20T14:27:28.539Z",
   "__v": 0,
   "startDate": "2018-01-20T14:21:28.539Z"
}]

= La gueule d'un track, c'est quoi ?
{
   "_id": "5a6350688fb12f001481b340",
   "name": "test",
   "info": "ceci est un test",
   "userId": "5a5e6f43734d1d3471851818",
   "endSeedId": "5a5e7207734d1d347185195c",
   "endDate": "2018-01-20T14:27:28.539Z",
   "__v": 0,
   "startDate": "2018-01-20T14:21:28.539Z"
}

= Les tracks du test :
[
      {
      "_id": "5a635eff8fb12f001481b342",
      "__v": 0,
      "lon": 0.1947279,
      "lat": 47.9937519,
      "timestamp": "2017-12-16T10:15:23.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b343",
      "__v": 0,
      "lon": 0.1948159,
      "lat": 47.9937823,
      "timestamp": "2017-12-16T10:15:22.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b344",
      "__v": 0,
      "lon": 0.1948849,
      "lat": 47.9938337,
      "timestamp": "2017-12-16T10:15:21.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b345",
      "__v": 0,
      "lon": 0.1949447,
      "lat": 47.9938867,
      "timestamp": "2017-12-16T10:15:20.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b346",
      "__v": 0,
      "lon": 0.195025,
      "lat": 47.9939204,
      "timestamp": "2017-12-16T10:15:19.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b347",
      "__v": 0,
      "lon": 0.1952061,
      "lat": 47.9939231,
      "timestamp": "2017-12-16T10:15:17.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b348",
      "__v": 0,
      "lon": 0.1952848,
      "lat": 47.993891,
      "timestamp": "2017-12-16T10:15:16.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b349",
      "__v": 0,
      "lon": 0.1953259,
      "lat": 47.993831,
      "timestamp": "2017-12-16T10:15:15.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b34a",
      "__v": 0,
      "lon": 0.1953596,
      "lat": 47.9936744,
      "timestamp": "2017-12-16T10:15:12.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b34b",
      "__v": 0,
      "lon": 0.1953659,
      "lat": 47.9936497,
      "timestamp": "2017-12-16T10:15:11.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b34c",
      "__v": 0,
      "lon": 0.195383,
      "lat": 47.993623,
      "timestamp": "2017-12-16T10:15:09.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b34d",
      "__v": 0,
      "lon": 0.1954212,
      "lat": 47.9935982,
      "timestamp": "2017-12-16T10:15:08.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b34e",
      "__v": 0,
      "lon": 0.1954694,
      "lat": 47.9935629,
      "timestamp": "2017-12-16T10:15:07.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b34f",
      "__v": 0,
      "lon": 0.1955508,
      "lat": 47.9935146,
      "timestamp": "2017-12-16T10:15:06.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b350",
      "__v": 0,
      "lon": 0.1956391,
      "lat": 47.9934771,
      "timestamp": "2017-12-16T10:15:05.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b351",
      "__v": 0,
      "lon": 0.1957288,
      "lat": 47.9934484,
      "timestamp": "2017-12-16T10:15:04.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b352",
      "__v": 0,
      "lon": 0.1958237,
      "lat": 47.9934276,
      "timestamp": "2017-12-16T10:15:03.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b353",
      "__v": 0,
      "lon": 0.1959273,
      "lat": 47.9933863,
      "timestamp": "2017-12-16T10:15:02.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b354",
      "__v": 0,
      "lon": 0.1960403,
      "lat": 47.9933597,
      "timestamp": "2017-12-16T10:15:01.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b355",
      "__v": 0,
      "lon": 0.196152,
      "lat": 47.9933329,
      "timestamp": "2017-12-16T10:15:00.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b356",
      "__v": 0,
      "lon": 0.1962505,
      "lat": 47.9933036,
      "timestamp": "2017-12-16T10:14:59.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b357",
      "__v": 0,
      "lon": 0.1963573,
      "lat": 47.9932767,
      "timestamp": "2017-12-16T10:14:58.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b358",
      "__v": 0,
      "lon": 0.1964591,
      "lat": 47.9932492,
      "timestamp": "2017-12-16T10:14:57.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b359",
      "__v": 0,
      "lon": 0.1965544,
      "lat": 47.9932087,
      "timestamp": "2017-12-16T10:14:56.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b35a",
      "__v": 0,
      "lon": 0.1966849,
      "lat": 47.9931733,
      "timestamp": "2017-12-16T10:14:55.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b35b",
      "__v": 0,
      "lon": 0.1968174,
      "lat": 47.993144,
      "timestamp": "2017-12-16T10:14:54.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b35c",
      "__v": 0,
      "lon": 0.1969467,
      "lat": 47.9931167,
      "timestamp": "2017-12-16T10:14:53.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b35d",
      "__v": 0,
      "lon": 0.1970625,
      "lat": 47.9930804,
      "timestamp": "2017-12-16T10:14:52.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b35e",
      "__v": 0,
      "lon": 0.1971685,
      "lat": 47.9930354,
      "timestamp": "2017-12-16T10:14:51.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b35f",
      "__v": 0,
      "lon": 0.197252,
      "lat": 47.9929652,
      "timestamp": "2017-12-16T10:14:50.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b360",
      "__v": 0,
      "lon": 0.1973062,
      "lat": 47.9928795,
      "timestamp": "2017-12-16T10:14:49.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b361",
      "__v": 0,
      "lon": 0.1973716,
      "lat": 47.9927984,
      "timestamp": "2017-12-16T10:14:48.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b362",
      "__v": 0,
      "lon": 0.1974562,
      "lat": 47.9927221,
      "timestamp": "2017-12-16T10:14:47.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b363",
      "__v": 0,
      "lon": 0.1975262,
      "lat": 47.9926318,
      "timestamp": "2017-12-16T10:14:46.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b364",
      "__v": 0,
      "lon": 0.1976,
      "lat": 47.992545,
      "timestamp": "2017-12-16T10:14:45.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b365",
      "__v": 0,
      "lon": 0.1976727,
      "lat": 47.992461,
      "timestamp": "2017-12-16T10:14:44.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b366",
      "__v": 0,
      "lon": 0.1977419,
      "lat": 47.9923797,
      "timestamp": "2017-12-16T10:14:43.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b367",
      "__v": 0,
      "lon": 0.1978071,
      "lat": 47.9923005,
      "timestamp": "2017-12-16T10:14:42.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b368",
      "__v": 0,
      "lon": 0.197873,
      "lat": 47.9922184,
      "timestamp": "2017-12-16T10:14:41.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b369",
      "__v": 0,
      "lon": 0.1980055,
      "lat": 47.9920699,
      "timestamp": "2017-12-16T10:14:39.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b36a",
      "__v": 0,
      "lon": 0.198064,
      "lat": 47.9919914,
      "timestamp": "2017-12-16T10:14:38.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b36b",
      "__v": 0,
      "lon": 0.1981273,
      "lat": 47.9919147,
      "timestamp": "2017-12-16T10:14:37.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b36c",
      "__v": 0,
      "lon": 0.198269,
      "lat": 47.9917227,
      "timestamp": "2017-12-16T10:14:34.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b36d",
      "__v": 0,
      "lon": 0.1982949,
      "lat": 47.9916988,
      "timestamp": "2017-12-16T10:14:33.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b36e",
      "__v": 0,
      "lon": 0.1982971,
      "lat": 47.9916749,
      "timestamp": "2017-12-16T10:14:30.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b36f",
      "__v": 0,
      "lon": 0.1983058,
      "lat": 47.9916254,
      "timestamp": "2017-12-16T10:14:29.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b370",
      "__v": 0,
      "lon": 0.1983394,
      "lat": 47.9916078,
      "timestamp": "2017-12-16T10:14:28.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b371",
      "__v": 0,
      "lon": 0.1983854,
      "lat": 47.9915447,
      "timestamp": "2017-12-16T10:14:27.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b372",
      "__v": 0,
      "lon": 0.1984383,
      "lat": 47.9914833,
      "timestamp": "2017-12-16T10:14:26.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b373",
      "__v": 0,
      "lon": 0.1984965,
      "lat": 47.991411,
      "timestamp": "2017-12-16T10:14:25.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b374",
      "__v": 0,
      "lon": 0.1985566,
      "lat": 47.9913239,
      "timestamp": "2017-12-16T10:14:24.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b375",
      "__v": 0,
      "lon": 0.198635,
      "lat": 47.9912348,
      "timestamp": "2017-12-16T10:14:23.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b376",
      "__v": 0,
      "lon": 0.1987085,
      "lat": 47.9911502,
      "timestamp": "2017-12-16T10:14:22.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b377",
      "__v": 0,
      "lon": 0.1987745,
      "lat": 47.9910671,
      "timestamp": "2017-12-16T10:14:21.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b378",
      "__v": 0,
      "lon": 0.1988415,
      "lat": 47.990983,
      "timestamp": "2017-12-16T10:14:20.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b379",
      "__v": 0,
      "lon": 0.1988964,
      "lat": 47.9908979,
      "timestamp": "2017-12-16T10:14:19.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b37a",
      "__v": 0,
      "lon": 0.1990473,
      "lat": 47.9907463,
      "timestamp": "2017-12-16T10:14:16.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b37b",
      "__v": 0,
      "lon": 0.1990703,
      "lat": 47.9907278,
      "timestamp": "2017-12-16T10:14:15.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b37c",
      "__v": 0,
      "lon": 0.1990884,
      "lat": 47.9907142,
      "timestamp": "2017-12-16T10:14:13.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b37d",
      "__v": 0,
      "lon": 0.1991063,
      "lat": 47.9907002,
      "timestamp": "2017-12-16T10:14:12.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b37e",
      "__v": 0,
      "lon": 0.1991454,
      "lat": 47.990679,
      "timestamp": "2017-12-16T10:14:11.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b37f",
      "__v": 0,
      "lon": 0.1991897,
      "lat": 47.990622,
      "timestamp": "2017-12-16T10:14:10.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b380",
      "__v": 0,
      "lon": 0.1992336,
      "lat": 47.9905552,
      "timestamp": "2017-12-16T10:14:09.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b381",
      "__v": 0,
      "lon": 0.1992839,
      "lat": 47.9904837,
      "timestamp": "2017-12-16T10:14:09.501Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b382",
      "__v": 0,
      "lon": 0.1992839,
      "lat": 47.9904837,
      "timestamp": "2017-12-16T10:14:08.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b383",
      "__v": 0,
      "lon": 0.199346,
      "lat": 47.990405,
      "timestamp": "2017-12-16T10:14:07.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b384",
      "__v": 0,
      "lon": 0.19941,
      "lat": 47.9903258,
      "timestamp": "2017-12-16T10:14:06.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b385",
      "__v": 0,
      "lon": 0.199482,
      "lat": 47.9902431,
      "timestamp": "2017-12-16T10:14:05.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b386",
      "__v": 0,
      "lon": 0.1995567,
      "lat": 47.9901606,
      "timestamp": "2017-12-16T10:14:04.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b387",
      "__v": 0,
      "lon": 0.199625,
      "lat": 47.9900862,
      "timestamp": "2017-12-16T10:14:03.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b388",
      "__v": 0,
      "lon": 0.1996809,
      "lat": 47.9900249,
      "timestamp": "2017-12-16T10:14:02.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b389",
      "__v": 0,
      "lon": 0.1997303,
      "lat": 47.9899832,
      "timestamp": "2017-12-16T10:14:01.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b38a",
      "__v": 0,
      "lon": 0.1997982,
      "lat": 47.9899198,
      "timestamp": "2017-12-16T10:13:59.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b38b",
      "__v": 0,
      "lon": 0.1998213,
      "lat": 47.9899034,
      "timestamp": "2017-12-16T10:13:56.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b38c",
      "__v": 0,
      "lon": 0.1998375,
      "lat": 47.9898856,
      "timestamp": "2017-12-16T10:13:55.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b38d",
      "__v": 0,
      "lon": 0.1998866,
      "lat": 47.9898461,
      "timestamp": "2017-12-16T10:13:54.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b38e",
      "__v": 0,
      "lon": 0.1999347,
      "lat": 47.9897864,
      "timestamp": "2017-12-16T10:13:53.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b38f",
      "__v": 0,
      "lon": 0.1999968,
      "lat": 47.9897233,
      "timestamp": "2017-12-16T10:13:52.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b390",
      "__v": 0,
      "lon": 0.2000543,
      "lat": 47.9896509,
      "timestamp": "2017-12-16T10:13:51.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b391",
      "__v": 0,
      "lon": 0.2001125,
      "lat": 47.9895669,
      "timestamp": "2017-12-16T10:13:50.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b392",
      "__v": 0,
      "lon": 0.2001758,
      "lat": 47.9894876,
      "timestamp": "2017-12-16T10:13:49.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b393",
      "__v": 0,
      "lon": 0.1916924,
      "lat": 47.9945019,
      "timestamp": "2017-12-16T10:15:43.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b394",
      "__v": 0,
      "lon": 0.1918422,
      "lat": 47.9944673,
      "timestamp": "2017-12-16T10:15:42.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b395",
      "__v": 0,
      "lon": 0.1919992,
      "lat": 47.9944275,
      "timestamp": "2017-12-16T10:15:41.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b396",
      "__v": 0,
      "lon": 0.1921622,
      "lat": 47.9943783,
      "timestamp": "2017-12-16T10:15:40.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b397",
      "__v": 0,
      "lon": 0.1923292,
      "lat": 47.9943378,
      "timestamp": "2017-12-16T10:15:39.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b398",
      "__v": 0,
      "lon": 0.1924918,
      "lat": 47.9942854,
      "timestamp": "2017-12-16T10:15:38.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b399",
      "__v": 0,
      "lon": 0.1926632,
      "lat": 47.9942468,
      "timestamp": "2017-12-16T10:15:37.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b39a",
      "__v": 0,
      "lon": 0.1928241,
      "lat": 47.9942118,
      "timestamp": "2017-12-16T10:15:36.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b39b",
      "__v": 0,
      "lon": 0.1929854,
      "lat": 47.9941609,
      "timestamp": "2017-12-16T10:15:35.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b39c",
      "__v": 0,
      "lon": 0.1931467,
      "lat": 47.9941216,
      "timestamp": "2017-12-16T10:15:34.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b39d",
      "__v": 0,
      "lon": 0.193304,
      "lat": 47.9940749,
      "timestamp": "2017-12-16T10:15:33.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b39e",
      "__v": 0,
      "lon": 0.1934681,
      "lat": 47.9940405,
      "timestamp": "2017-12-16T10:15:32.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b39f",
      "__v": 0,
      "lon": 0.193627,
      "lat": 47.9939991,
      "timestamp": "2017-12-16T10:15:31.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a0",
      "__v": 0,
      "lon": 0.1937905,
      "lat": 47.9939564,
      "timestamp": "2017-12-16T10:15:30.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a1",
      "__v": 0,
      "lon": 0.1939486,
      "lat": 47.9939166,
      "timestamp": "2017-12-16T10:15:29.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a2",
      "__v": 0,
      "lon": 0.1940936,
      "lat": 47.9938796,
      "timestamp": "2017-12-16T10:15:28.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a3",
      "__v": 0,
      "lon": 0.1942315,
      "lat": 47.9938409,
      "timestamp": "2017-12-16T10:15:27.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a4",
      "__v": 0,
      "lon": 0.1943688,
      "lat": 47.9938039,
      "timestamp": "2017-12-16T10:15:26.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a5",
      "__v": 0,
      "lon": 0.1944977,
      "lat": 47.9937699,
      "timestamp": "2017-12-16T10:15:25.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a6",
      "__v": 0,
      "lon": 0.194616,
      "lat": 47.9937469,
      "timestamp": "2017-12-16T10:15:24.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a7",
      "__v": 0,
      "lon": 0.2002374,
      "lat": 47.989422,
      "timestamp": "2017-12-16T10:13:48.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a8",
      "__v": 0,
      "lon": 0.200343,
      "lat": 47.9893014,
      "timestamp": "2017-12-16T10:13:45.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3a9",
      "__v": 0,
      "lon": 0.2003569,
      "lat": 47.9892878,
      "timestamp": "2017-12-16T10:13:43.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3aa",
      "__v": 0,
      "lon": 0.2003692,
      "lat": 47.9892759,
      "timestamp": "2017-12-16T10:13:42.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3ab",
      "__v": 0,
      "lon": 0.200393,
      "lat": 47.9892456,
      "timestamp": "2017-12-16T10:13:41.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3ac",
      "__v": 0,
      "lon": 0.200436,
      "lat": 47.9891898,
      "timestamp": "2017-12-16T10:13:40.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3ad",
      "__v": 0,
      "lon": 0.2004917,
      "lat": 47.9891316,
      "timestamp": "2017-12-16T10:13:39.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3ae",
      "__v": 0,
      "lon": 0.2005521,
      "lat": 47.9890633,
      "timestamp": "2017-12-16T10:13:38.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3af",
      "__v": 0,
      "lon": 0.2006132,
      "lat": 47.9889899,
      "timestamp": "2017-12-16T10:13:37.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b0",
      "__v": 0,
      "lon": 0.200681,
      "lat": 47.9889143,
      "timestamp": "2017-12-16T10:13:36.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b1",
      "__v": 0,
      "lon": 0.2007444,
      "lat": 47.988835,
      "timestamp": "2017-12-16T10:13:35.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b2",
      "__v": 0,
      "lon": 0.2008216,
      "lat": 47.9887481,
      "timestamp": "2017-12-16T10:13:34.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b3",
      "__v": 0,
      "lon": 0.2008958,
      "lat": 47.9886675,
      "timestamp": "2017-12-16T10:13:33.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b4",
      "__v": 0,
      "lon": 0.2009656,
      "lat": 47.9885869,
      "timestamp": "2017-12-16T10:13:32.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b5",
      "__v": 0,
      "lon": 0.2010358,
      "lat": 47.9885087,
      "timestamp": "2017-12-16T10:13:31.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b6",
      "__v": 0,
      "lon": 0.2010999,
      "lat": 47.9884361,
      "timestamp": "2017-12-16T10:13:30.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b7",
      "__v": 0,
      "lon": 0.2011728,
      "lat": 47.9883701,
      "timestamp": "2017-12-16T10:13:29.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b8",
      "__v": 0,
      "lon": 0.2012298,
      "lat": 47.9883085,
      "timestamp": "2017-12-16T10:13:28.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3b9",
      "__v": 0,
      "lon": 0.2012836,
      "lat": 47.9882503,
      "timestamp": "2017-12-16T10:13:27.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3ba",
      "__v": 0,
      "lon": 0.2013242,
      "lat": 47.9881949,
      "timestamp": "2017-12-16T10:13:26.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3bb",
      "__v": 0,
      "lon": 0.2013701,
      "lat": 47.9881499,
      "timestamp": "2017-12-16T10:13:25.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3bc",
      "__v": 0,
      "lon": 0.201419,
      "lat": 47.9880958,
      "timestamp": "2017-12-16T10:13:24.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3bd",
      "__v": 0,
      "lon": 0.2014619,
      "lat": 47.9880686,
      "timestamp": "2017-12-16T10:13:23.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3be",
      "__v": 0,
      "lon": 0.2015073,
      "lat": 47.9880276,
      "timestamp": "2017-12-16T10:13:22.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3bf",
      "__v": 0,
      "lon": 0.2016,
      "lat": 47.9879901,
      "timestamp": "2017-12-16T10:13:20.000Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3c0",
      "__v": 0,
      "lon": 0.2015876,
      "lat": 47.9879727,
      "timestamp": "2017-12-16T10:13:19.766Z",
      "trackId": "5a6350688fb12f001481b340"
   },
      {
      "_id": "5a635eff8fb12f001481b3c1",
      "__v": 0,
      "lon": 0.2012927,
      "lat": 47.9879051,
      "timestamp": "2017-12-16T10:13:18.271Z",
      "trackId": "5a6350688fb12f001481b340"
   }
]

== overpass


= Recuperer les routes de type tertiary donc un rectangle donné
[out:json];
way(47.984393,0.236012,47.984946,0.238951)[highway=tertiary];
(._;>;);

out;


https://wiki.openstreetmap.org/wiki/Map_Features

=======
// Javascript
function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
  var R = 6371; // Radius of the earth in km
  var dLat = deg2rad(lat2-lat1);  // deg2rad below
  var dLon = deg2rad(lon2-lon1); 
  var a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
    Math.sin(dLon/2) * Math.sin(dLon/2)
    ; 
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
  var d = R * c; // Distance in km
  return d;
}

function deg2rad(deg) {
  return deg * (Math.PI/180)
}


