==== partage 

== serveur 

= recuperer le token pour la fourmi

curl -d "email=ant1@violet.ant&password=Prune" -X POST https://f24h2018.herokuapp.com/auth/local

= recuperer le token pour la cigale

curl -d "email=cicada@violet.ant&password=Prune" -X POST https://f24h2018.herokuapp.com/auth/local

= recuperer les graines (exemple)
Requête :
GET https://f24h2018.herokuapp.com/api/Seeds/search HTTP/1.1
Accept-Encoding: gzip,deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTYzMjMyN2YzNmQyODcwODdhMTk2YWUiLCJyb2xlIjoiY2ljYWRhIiwiaWF0IjoxNTE2NDQ4NTU5LCJleHAiOjE1MTY0NjY1NTl9.vRC4yJZ_HmY-vrr5tFbgXvbh6tjuLIPtlOyzl1jwgZQ
Host: f24h2018.herokuapp.com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

Réponse :
[
      {
      "_id": "5a5e71a2734d1d347185192c",
      "name": "La fourmilière",
      "info": "Colonie",
      "active": true,
      "type": "home",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.9844782,
            0.2415538
         ]
      }
   },
      {
      "_id": "5a5e7207734d1d347185195c",
      "name": "Epau",
      "info": "pas trop loin",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.99026,
            0.23991
         ]
      }
   },
      {
      "_id": "5a5e7228734d1d3471851968",
      "name": "CFA",
      "info": "pas trop loin",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.9827689,
            0.2328369
         ]
      }
   },
      {
      "_id": "5a5e71e2734d1d3471851942",
      "name": "Les plaines de l'arche",
      "info": "pas trop loin",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.987444,
            0.253475
         ]
      }
   },
      {
      "_id": "5a63483cf36d287087a19f59",
      "name": "Goncourt",
      "info": "après lycée Sud",
      "active": true,
      "type": "seed",
      "location":       {
         "type": "Point",
         "coordinates":          [
            47.9809281,
            0.2222387
         ]
      }
   }
]

== overpass


= Recuperer les routes de type tertiary donc un rectangle donné
[out:json];
way(47.984393,0.236012,47.984946,0.238951)[highway=tertiary];
(._;>;);

out;


https://wiki.openstreetmap.org/wiki/Map_Features

=======
// Javascript
function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
  var R = 6371; // Radius of the earth in km
  var dLat = deg2rad(lat2-lat1);  // deg2rad below
  var dLon = deg2rad(lon2-lon1); 
  var a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
    Math.sin(dLon/2) * Math.sin(dLon/2)
    ; 
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
  var d = R * c; // Distance in km
  return d;
}

function deg2rad(deg) {
  return deg * (Math.PI/180)
}

= Liste des tracks des autres équipes

Réponse :
[{
   "_id": "5a6350688fb12f001481b340",
   "name": "test",
   "info": "ceci est un test",
   "userId": "5a5e6f43734d1d3471851818",
   "endSeedId": "5a5e7207734d1d347185195c",
   "endDate": "2018-01-20T14:27:28.539Z",
   "__v": 0,
   "startDate": "2018-01-20T14:21:28.539Z"
}]
